# Generated by Django 4.1.7 on 2023-06-05 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
            ],
            options={
                'verbose_name': 'Площадь',
                'verbose_name_plural': 'Площадь',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.area')),
            ],
            options={
                'verbose_name': 'Координаты',
                'verbose_name_plural': 'Координаты',
            },
        ),
        migrations.CreateModel(
            name='Precipitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
            ],
            options={
                'verbose_name': 'Осадки',
                'verbose_name_plural': 'Осадки',
            },
        ),
        migrations.CreateModel(
            name='PrecipitationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Тип осадков',
                'verbose_name_plural': 'Тип осадков',
            },
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.position')),
                ('precipitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.precipitation')),
            ],
            options={
                'verbose_name': 'Общее',
                'verbose_name_plural': 'Общее',
            },
        ),
        migrations.AddField(
            model_name='precipitation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.precipitationtype'),
        ),
    ]
